# This line should trigger Travis to use the container infrastructure.
sudo: false
# @todo, determine how best to use Travis build caches.
language: php

php:
  # @todo add php 7.
  - 5.5
  - 5.6


env:
  global:
    - MODULE_NAME='template_mapper'
    - MODULE_TEST_GROUP='template_mapper'
    - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
    - DRUPAL_VERSION='8.0.x'

matrix:
  allow-failures:
    - php: 5.5

before_install:

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  # - composer self-update

  # Drush.
  - composer global require "youngj/httpserver:dev-master#41dd2b7"
  - composer global require drush/drush:dev-master

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:
  # Basic PHP packages.
  #- sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Move the checked out module into the correct structure.
  - mkdir /tmp/$MODULE_NAME
  - mv * /tmp/$MODULE_NAME/
  - git clone --branch $DRUPAL_VERSION $DRUPAL_REPO drupal --depth 1
  - mv /tmp/$MODULE_NAME drupal/modules/

before_script:
  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Mysql might time out for long tests, increase the wait timeout.
  - mysql -e 'SET @@GLOBAL.wait_timeout=1200'

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'
  # @todo, don't use the standard profile.
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes site-install standard --db-url="mysql://root@127.0.0.1/drupal"
  - cd $TRAVIS_BUILD_DIR/drupal/modules/template_mapper/tests && composer install --prefer-source --no-interaction
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes en $MODULE_NAME

  # Start a web server.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  # Run code sniffer.
  - cd $TRAVIS_BUILD_DIR/drupal/modules/template_mapper/tests && ./vendor/bin/behat -f pretty --config behat.travis.yml
  - cd $TRAVIS_BUILD_DIR/drupal/core && ./vendor/bin/phpunit  --group template_mapper
